version: "3.8"
services:

  appsito:
    build:
      context: .
    command: uvicorn main:app --reload --proxy-headers --host 0.0.0.0 --port 82
    expose:
      - 82
    volumes:
      - ./app:/api/
    environment:
      - RUTA_MONGO=${RUTA_MONGO}

  nginx:
    image: nginx:latest
    # ports:
    #   - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=api-products.diego-luque.com
      - LETSENCRYPT_HOST=api-products.diego-luque.com

networks:
  default:
    name: web_private_red_webapps
    external: true
